version: 2.1
orbs:
  ansible-playbook: orbss/ansible-playbook@0.0.5
jobs:
  build: 
    executor: ansible-playbook/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:NtcsrJONxgN+HxBqvRPu52Rh+itJe47yz5ke5cMmiaQ"
      - ansible-playbook/install:
          version: 2.10.7
      - ansible-playbook/playbook:
          playbook: ansible/playbook.yml
          playbook-options: -u ec2-user -i ansible/inventory --private-key ~/.ssh/id_rsa
workflows:
  version: 2
  ansibledeploy:
    jobs:
      - build
